apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-playground-deployment
  labels:
    app: argo-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-playground
  template:
    metadata:
      labels:
        app: argo-playground
    spec:
      containers:
        - name: argo-playground
          image: shashankssriva/mymusicstats-arm64:1.0.2
          ports:
            - containerPort: 80